---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqttbridge
  labels:
    app.kubernetes.io/name: mqttbridge
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mqttbridge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mqttbridge
    spec:
      containers:
        - name: mqttbridge
          image: mqttbridge
          env:
            - name: GOWON_BROKER
              value: mosquitto:1883
            - name: GOWON_HOST
              value: http://gowon:8080
          ports:
            - containerPort: 8080
              name: http
