---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: module1
  labels:
    app.kubernetes.io/name: module1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: module1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: module1
    spec:
      containers:
        - name: module1
          image: module1
          env:
            - name: GOWON_BROKER
              value: mosquitto:1883
